/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas;

import controladores.ControlaAnimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import modelos.Animal;

/**
 *
 * @author leonardo.bourscheid
 */
public class CadastroAnimal extends javax.swing.JDialog {

    private static DateTimeFormatter FORMATO_1 = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    ControlaAnimal controlaAnimal;
    TelaListagemAnimal telaListagemAnimal;
    Animal animalEditado = null;

    /**
     * Creates new form CadastroAnimal
     */
    //Contrutor tela de cadastro
    public CadastroAnimal(java.awt.Frame parent, boolean modal, ControlaAnimal ca, TelaListagemAnimal tl) {
        super(parent, modal);
        initComponents();
        this.controlaAnimal = ca;
        this.telaListagemAnimal = tl;
    }

    //Construtor tela de ediçao
    public CadastroAnimal(java.awt.Frame parent, boolean modal, ControlaAnimal ca, TelaListagemAnimal tl, Integer codAnimal) {
        super(parent, modal);
        initComponents();
        this.controlaAnimal = ca;
        this.telaListagemAnimal = tl;
        this.animalEditado = controlaAnimal.recuperarAnimal(codAnimal);

        txtTipoAnimal.setText(animalEditado.getTipo());
        txtDataEncontro.setText(animalEditado.getDataEncontro().format(FORMATO_1));
        txtRaca.setText(animalEditado.getRaca());
        txtSexo.setText(animalEditado.getSexo().toString());
        txtCor.setText(animalEditado.getCor());
        txtLocalDeEncontro.setText(animalEditado.getLocalDeEncontro());

        if (animalEditado.getIdade() != 0) {
            txtIdade.setText(String.valueOf(animalEditado.getIdade()));
        }

        if (!animalEditado.getNome().equals("null")) {
            txtNome.setText(animalEditado.getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCor = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtIdade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLocalDeEncontro = new javax.swing.JTextArea();
        lblTipoAnimal = new javax.swing.JLabel();
        txtTipoAnimal = new javax.swing.JTextField();
        lblDataEncontro = new javax.swing.JLabel();
        txtDataEncontro = new javax.swing.JTextField();
        lblRaca = new javax.swing.JLabel();
        txtRaca = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        txtSexo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCor.setText("Cor:*");

        lblNome.setText("Nome:");

        jLabel1.setText("Idade:");

        txtIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdadeActionPerformed(evt);
            }
        });

        jLabel2.setText("Local de encontro:*");

        txtLocalDeEncontro.setColumns(20);
        txtLocalDeEncontro.setRows(5);
        txtLocalDeEncontro.setLineWrap(true);

        txtLocalDeEncontro.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtLocalDeEncontro);

        lblTipoAnimal.setText("Tipo animal:*");

        txtTipoAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoAnimalActionPerformed(evt);
            }
        });

        lblDataEncontro.setText("Data de encontro:*");

        txtDataEncontro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataEncontroActionPerformed(evt);
            }
        });

        lblRaca.setText("Raça:*");

        txtRaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRacaActionPerformed(evt);
            }
        });

        lblSexo.setText("Sexo:*");

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTipoAnimal, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTipoAnimal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                .addComponent(lblRaca, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtRaca, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtIdade, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lblNome))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDataEncontro)
                            .addComponent(txtDataEncontro)
                            .addComponent(lblSexo)
                            .addComponent(txtSexo)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTipoAnimal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTipoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDataEncontro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataEncontro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRaca)
                    .addComponent(lblSexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCor)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdadeActionPerformed

    private void txtTipoAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoAnimalActionPerformed

    private void txtDataEncontroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataEncontroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataEncontroActionPerformed

    private void txtRacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRacaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (animalEditado != null) {

            animalEditado.setTipo(txtTipoAnimal.getText().toUpperCase());
            animalEditado.setDataEncontro(LocalDate.parse(txtDataEncontro.getText(), FORMATO_1));
            animalEditado.setRaca(txtRaca.getText().toUpperCase());
            animalEditado.setCor(txtCor.getText().toUpperCase());
            animalEditado.setSexo(txtSexo.getText().trim().toUpperCase().charAt(0));
            animalEditado.setLocalDeEncontro(txtLocalDeEncontro.getText().toUpperCase());

            if (!txtIdade.getText().trim().equals("")) {
                animalEditado.setIdade(Integer.valueOf(txtIdade.getText()));
            }

            if (!txtNome.getText().trim().equals("")) {
                animalEditado.setNome(txtNome.getText().trim().toUpperCase());
            }

            boolean deuCerto = controlaAnimal.editar(animalEditado);

            if (deuCerto) {
                JOptionPane.showMessageDialog(this, "EDITADO COM SUCESSO");
                telaListagemAnimal.montaTabela();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "ERRO AO EDITAR, TENTE NOVAMENTE");
            }

        } else {
            Animal animal = new Animal(txtTipoAnimal.getText().toUpperCase(),
                    LocalDate.parse(txtDataEncontro.getText(), FORMATO_1),
                    txtRaca.getText().toUpperCase(),
                    txtCor.getText().toUpperCase(),
                    txtSexo.getText().trim().toUpperCase().charAt(0),
                    txtLocalDeEncontro.getText().trim().toUpperCase());

            if (!txtIdade.getText().trim().equals("")) {
                animal.setIdade(Integer.valueOf(txtIdade.getText()));
            }

            if (!txtNome.getText().trim().equals("")) {
                animal.setNome(txtNome.getText().toUpperCase());
            }

            boolean deuCerto = controlaAnimal.salvar(animal);

            if (deuCerto) {
                JOptionPane.showMessageDialog(null, "Salvo com sucesso!");

                txtTipoAnimal.setText("");
                txtDataEncontro.setText("");
                txtRaca.setText("");
                txtSexo.setText("");
                txtCor.setText("");
                txtLocalDeEncontro.setText("");
                txtIdade.setText("");
                txtNome.setText("");

                telaListagemAnimal.montaTabela();
            } else {
                JOptionPane.showMessageDialog(this, "ERRO! Tente novamente mais tarde:");
            }
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroAnimal dialog = new CadastroAnimal(new javax.swing.JFrame(), true, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblDataEncontro;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRaca;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTipoAnimal;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtDataEncontro;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextArea txtLocalDeEncontro;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRaca;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTipoAnimal;
    // End of variables declaration//GEN-END:variables
}
