/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas;

import controladores.ControlaAdocao;
import controladores.ControlaAnimal;
import controladores.ControlaPessoa;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import modelos.Adocao;
import static modelos.Adocao.Status.CONFIRMADO;
import static modelos.Adocao.Status.PENDENTE;
import modelos.Animal;
import modelos.ComboItem;
import modelos.DAO.CombosDAO;
import modelos.Pessoa;

/**
 *
 * @author leonardobourscheid
 */
public class CadastroAdocao extends javax.swing.JDialog {
    
    ControlaAdocao controlaAdocao = ControlaAdocao.getInstance();
    ControlaPessoa controlaPessoa = ControlaPessoa.getInstance();
    ControlaAnimal controlaAnimal = ControlaAnimal.getInstance();
    
    TelaListagemAdocao listagemAdocao = TelaListagemAdocao.getInstance();
    
    Adocao adocaoEditada;
    
    /**
     * Creates new form CadastroAnimal2
     */
    public CadastroAdocao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        new CombosDAO().popularCombo("pessoa", "cod_pessoa", "nom_pessoa" , cmbAdotante, "");
        new CombosDAO().popularCombo("animal", "cod_animal", "resumo_pet", cmbPet, "order by cod_animal");
        txtDevolucao.setEnabled(false);
    }
    
    public CadastroAdocao(java.awt.Frame parent, boolean modal, Adocao adocao) {
        super(parent, modal);
        initComponents();
        
        new CombosDAO().popularCombo("pessoa", "cod_pessoa", "nom_pessoa" , cmbAdotante, "");
        new CombosDAO().popularCombo("animal", "cod_animal", "resumo_pet", cmbPet, "order by cod_animal");
        
        this.adocaoEditada = adocao;
        
        cmbAdotante.setSelectedIndex(adocao.getPessoa().getCodPessoa());
        cmbPet.setSelectedIndex(adocao.getAnimal().getCodAnimal());
        txtDevolucao.setText(adocao.getMotivoDevolucao());
        
        if (adocao.getStatus().equals(Adocao.Status.CONFIRMADO)) {
            cmbAdotante.setEnabled(false);
            cmbPet.setEnabled(false);
        } else if (adocao.getStatus().equals(Adocao.Status.PENDENTE)) {
            txtDevolucao.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdotante = new javax.swing.JLabel();
        lblPet = new javax.swing.JLabel();
        cmbAdotante = new javax.swing.JComboBox<>();
        cmbPet = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDevolucao = new javax.swing.JTextArea();
        lblDevolucao = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblAdotante.setText("ADOTANTE:*");

        lblPet.setText("PET:*");

        cmbAdotante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbPet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtDevolucao.setColumns(20);
        txtDevolucao.setRows(5);
        txtDevolucao.setLineWrap(true);

        txtDevolucao.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDevolucao);

        lblDevolucao.setText("MOTIVO DEVOLUÇÃO:");

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalvar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAdotante)
                            .addComponent(lblPet)
                            .addComponent(cmbAdotante, 0, 262, Short.MAX_VALUE)
                            .addComponent(cmbPet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDevolucao)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAdotante)
                .addGap(2, 2, 2)
                .addComponent(cmbAdotante, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPet)
                .addGap(2, 2, 2)
                .addComponent(cmbPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDevolucao)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (adocaoEditada != null) {

            adocaoEditada.setPessoa(controlaPessoa.recuperarPessoa(cmbAdotante.getSelectedIndex()));
            adocaoEditada.setAnimal(controlaAnimal.recuperarAnimal(cmbPet.getSelectedIndex()));

            if ( txtDevolucao.getText() != null && !txtDevolucao.getText().isBlank()
                && adocaoEditada.getStatus().equals(Adocao.Status.CONFIRMADO) )
            {
                adocaoEditada.setMotivoDevolucao(txtDevolucao.getText());
                adocaoEditada.setDataDevolucao(LocalDate.now());
                adocaoEditada.setStatus(Adocao.Status.DEVOLVIDO);
            }

            boolean deuCerto = controlaAdocao.editar(adocaoEditada);
            
            if (deuCerto) {
                
                switch (adocaoEditada.getStatus()) {
                    
                    case PENDENTE -> {
                        JOptionPane.showMessageDialog(this, "EDITADO COM SUCESSO!");
                    }
                    
                    case CONFIRMADO -> {
                        JOptionPane.showMessageDialog(this, "DEVOLVIDO COM SUCESSO!");
                    }
                    
                }
                
                this.dispose();
            }
            
            else {
                
                switch (adocaoEditada.getStatus()) {
                    
                    case PENDENTE -> {
                        JOptionPane.showMessageDialog(this, "ERRO AO EDITAR, TENTE NOVAMENTE!");
                    }
                    
                    case CONFIRMADO -> {
                        JOptionPane.showMessageDialog(this, "ERRO AO DEVOLVER, TENTE NOVAMENTE!");
                    }
                    
                }
            }

        } else {

            ComboItem pessoaCombo = (ComboItem) cmbAdotante.getSelectedItem();
            ComboItem animalCombo = (ComboItem) cmbPet.getSelectedItem();

            Pessoa p = controlaPessoa.recuperarPessoa(pessoaCombo.getCodigo());
            Animal a = controlaAnimal.recuperarAnimal(animalCombo.getCodigo());

            Adocao adocao = new Adocao(p, a, Adocao.Status.PENDENTE);

            boolean deuCerto = controlaAdocao.salvar(adocao);

            if (deuCerto) {
                JOptionPane.showMessageDialog(this, "SALVO COM SUCESSO!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "FALHA AO SALVAR, TENTE NOVAMENTE");
            }

        }

        listagemAdocao.montaTabela();
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                CadastroAdocao dialog = new CadastroAdocao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbAdotante;
    private javax.swing.JComboBox<String> cmbPet;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdotante;
    private javax.swing.JLabel lblDevolucao;
    private javax.swing.JLabel lblPet;
    private javax.swing.JTextArea txtDevolucao;
    // End of variables declaration//GEN-END:variables
}
