/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import apoio.PDFManager;
import apoio.Validacao;
import controladores.ControlaPessoa;
import modelos.Pessoa;

/**
 *
 * @author leonardo
 */
public class TelaPDFPessoa extends javax.swing.JInternalFrame {

    private ControlaPessoa controlaPessoa = new ControlaPessoa();

    /**
     * Creates new form TelaPDFPessoa
     */
    public TelaPDFPessoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCaminho = new javax.swing.JTextField();
        btnGerarPDF = new javax.swing.JButton();
        btnSelecionarCaminho = new javax.swing.JButton();

        setClosable(true);

        btnGerarPDF.setText("Gerar PDF");
        btnGerarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarPDFActionPerformed(evt);
            }
        });

        btnSelecionarCaminho.setText("Selecionar caminho");
        btnSelecionarCaminho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarCaminhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCaminho)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSelecionarCaminho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                        .addComponent(btnGerarPDF)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(txtCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGerarPDF)
                    .addComponent(btnSelecionarCaminho))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionarCaminhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarCaminhoActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Escolha um caminho para salvar o arquivo");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        
        int resultado = chooser.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File dir = chooser.getSelectedFile();
            txtCaminho.setText(dir.getAbsolutePath() + "/pessoas.pdf");
        }
    }//GEN-LAST:event_btnSelecionarCaminhoActionPerformed

    private void btnGerarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarPDFActionPerformed
        
        String caminho = txtCaminho.getText();
        ArrayList<Pessoa> pessoas = controlaPessoa.recuperarTudo();

        if (!pessoas.isEmpty()) {
            if (caminho.isBlank()) {
                JOptionPane.showMessageDialog(this, "VOCÊ PRECISA SELECIONAR UM CAMINHO PARA GERAR O PDF!");
            } else {
                try {
                    String[] ordem = {
                            "codPessoa",
                            "nomePessoa",
                            "documento",
                            "dataNascimento"
                    };

                    String[] rotulos = {
                            "Código",
                            "Nome",
                            "Documento",
                            "Data de Nascimento"
                    };

                    int[] larguras = {5, 16, 11, 14};

                    pessoas.forEach(Pessoa::getDocumento);

                    PDFManager.gerar(pessoas, caminho, ordem, larguras, rotulos);
                    JOptionPane.showMessageDialog(this, "PDF GERADO COM SUCESSO, NO CAMINHO: " + caminho);
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, "OCORREU UM ERRO AO GERAR O PDF, TENTE NOVAMENTE MAIS TARDE");
                    System.err.println("Erro ao salvar PDF: " + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "NÃO HÁ PESSOAS CADASTRADAS");
        }
        
    }//GEN-LAST:event_btnGerarPDFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarPDF;
    private javax.swing.JButton btnSelecionarCaminho;
    private javax.swing.JTextField txtCaminho;
    // End of variables declaration//GEN-END:variables
}
