/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import modelos.Usuario;

/**
 *
 * @author leonardo.bourscheid
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Usuario usuarioLogado;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(Usuario usuario) {
        initComponents();
        setLocationRelativeTo(null);
        this.usuarioLogado = usuario;
        if (!usuarioLogado.getUsuario().equals("admin")) {
            menuCadastros.remove(mnuUsuarios);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        dskPainel = new javax.swing.JDesktopPane();
        barraMenu = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        mnuPessoa = new javax.swing.JMenuItem();
        mnuAnimal = new javax.swing.JMenuItem();
        mnuAdocao = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        mnuPessoasPDF = new javax.swing.JMenuItem();
        mnuAnimaisPDF = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dskPainelLayout = new javax.swing.GroupLayout(dskPainel);
        dskPainel.setLayout(dskPainelLayout);
        dskPainelLayout.setHorizontalGroup(
            dskPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 743, Short.MAX_VALUE)
        );
        dskPainelLayout.setVerticalGroup(
            dskPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        menuCadastros.setText("Cadastros");

        mnuPessoa.setText("Pessoas");
        mnuPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPessoaActionPerformed(evt);
            }
        });
        menuCadastros.add(mnuPessoa);

        mnuAnimal.setText("Animais");
        mnuAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAnimalActionPerformed(evt);
            }
        });
        menuCadastros.add(mnuAnimal);

        mnuAdocao.setText("Adoção");
        mnuAdocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdocaoActionPerformed(evt);
            }
        });
        menuCadastros.add(mnuAdocao);

        mnuUsuarios.setText("Usuários");
        menuCadastros.add(mnuUsuarios);

        barraMenu.add(menuCadastros);

        menuRelatorios.setText("Relatorios");

        mnuPessoasPDF.setText("Pessoas Cadastradas");
        mnuPessoasPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPessoasPDFActionPerformed(evt);
            }
        });
        menuRelatorios.add(mnuPessoasPDF);

        mnuAnimaisPDF.setText("Animais Cadastrados");
        mnuAnimaisPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAnimaisPDFActionPerformed(evt);
            }
        });
        menuRelatorios.add(mnuAnimaisPDF);

        barraMenu.add(menuRelatorios);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPainel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPainel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPessoaActionPerformed
        TelaListagemPessoa telaListagemPessoa = new TelaListagemPessoa();
        dskPainel.add(telaListagemPessoa);
        telaListagemPessoa.setVisible(true);
    }//GEN-LAST:event_mnuPessoaActionPerformed

    private void mnuAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAnimalActionPerformed
        TelaListagemAnimal telaListagemAnimal = new TelaListagemAnimal();
        dskPainel.add(telaListagemAnimal);
        telaListagemAnimal.setVisible(true);
    }//GEN-LAST:event_mnuAnimalActionPerformed

    private void mnuPessoasPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPessoasPDFActionPerformed
        TelaPDFPessoa telaPDFPessoa = new TelaPDFPessoa();
        dskPainel.add(telaPDFPessoa);
        telaPDFPessoa.setVisible(true);
    }//GEN-LAST:event_mnuPessoasPDFActionPerformed

    private void mnuAdocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdocaoActionPerformed
        TelaListagemAdocao telaListagemAdocao = TelaListagemAdocao.getInstance();
        dskPainel.add(telaListagemAdocao);
        telaListagemAdocao.setVisible(true);
    }//GEN-LAST:event_mnuAdocaoActionPerformed

    private void mnuAnimaisPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAnimaisPDFActionPerformed
        TelaPDFAnimal telaPDFAnimal = new TelaPDFAnimal();
        dskPainel.add(telaPDFAnimal);
        telaPDFAnimal.setVisible(true);
    }//GEN-LAST:event_mnuAnimaisPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JDesktopPane dskPainel;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenuItem mnuAdocao;
    private javax.swing.JMenuItem mnuAnimaisPDF;
    private javax.swing.JMenuItem mnuAnimal;
    private javax.swing.JMenuItem mnuPessoa;
    private javax.swing.JMenuItem mnuPessoasPDF;
    private javax.swing.JMenuItem mnuUsuarios;
    // End of variables declaration//GEN-END:variables
}
