/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import apoio.Formatacao;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.AbstractTableModel;

import modelos.Pessoa;
import controladores.ControlaPessoa;

/**
 *
 * @author leonardo.bourscheid
 */
public class TelaListagemAdocao extends javax.swing.JInternalFrame {

    ControlaPessoa controlaPessoa = ControlaPessoa.getInstace();
    
    /**
     * Creates new form TelaListagemAdocao
     */
    public TelaListagemAdocao() {
        initComponents();
    }

    protected final void montaTabela() {
        ArrayList<Pessoa> pessoas = controlaPessoa.recuperarTudo();
        if (pessoas == null) {
            JOptionPane.showMessageDialog(this, "Erro, não foi possivel recuperar");
        } else {
            tblAdocao.setModel(new AbstractTableModel() {
                @Override
                public String getColumnName(int column) {
                    switch (column) {
                        case 0:
                            return "CÓDIGO";
                        case 1:
                            return "NOME";
                        case 2:
                            return "ENDERECO";
                        case 3:
                            return "DOCUMENTO";
                        case 4:
                            return "NASCIMENTO";
                        default:
                            return "";
                    }
                }

                @Override
                public int getColumnCount() {
                    return 5;
                }

                @Override
                public int getRowCount() {
                    return pessoas.size();
                }

                @Override
                public Object getValueAt(int rowIndex, int columnIndex) {
                    Pessoa pessoa = pessoas.get(rowIndex);
                    pessoas.forEach(Pessoa::defineDocumento);

                    if (pessoa != null) {
                        switch (columnIndex) {
                            case 0:
                                return pessoa.getCodPessoa();
                            case 1:
                                return pessoa.getNomePessoa();
                            case 2:
                                return pessoa.getEndereco().escreveEndereco();
                            case 3:
                                return pessoa.getDocumento();
                            case 4:
                                return pessoa.getDataNascimento().format(Formatacao.FORMATO_1);
                        }

                    }

                    return "n/d";
                }
            });

            tblAdocao.getColumnModel().getColumn(0).setMinWidth(65);
            tblAdocao.getColumnModel().getColumn(1).setMinWidth(180);
            tblAdocao.getColumnModel().getColumn(2).setMinWidth(180);
            tblAdocao.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblAdocao.getColumnModel().getColumn(0).setMaxWidth(20);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastra = new javax.swing.JButton();
        btnAtualiza = new javax.swing.JButton();
        btnEdita = new javax.swing.JButton();
        btnDeleta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdocao = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(655, 507));
        setPreferredSize(new java.awt.Dimension(655, 507));

        btnCadastra.setText("CADASTRA");
        btnCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastraActionPerformed(evt);
            }
        });

        btnAtualiza.setText("ATUALIZA");
        btnAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizaActionPerformed(evt);
            }
        });

        btnEdita.setText("EDITA");
        btnEdita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditaActionPerformed(evt);
            }
        });

        btnDeleta.setText("DELETA");
        btnDeleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletaActionPerformed(evt);
            }
        });

        tblAdocao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAdocao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtualiza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleta)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastra)
                    .addComponent(btnAtualiza)
                    .addComponent(btnEdita)
                    .addComponent(btnDeleta))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastraActionPerformed
        JFrame telaAnterior = (JFrame) SwingUtilities.getWindowAncestor(this);
        CadastroAdocao telaCadastroAdocao = new CadastroAdocao();
        telaCadastroAdocao.setLocationRelativeTo(telaAnterior);
        telaCadastroAdocao.setVisible(true);
    }//GEN-LAST:event_btnCadastraActionPerformed

    private void btnAtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizaActionPerformed
        montaTabela();
    }//GEN-LAST:event_btnAtualizaActionPerformed

    private void btnEditaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditaActionPerformed

        if (tblAdocao.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "SÓ ESQUECEU DE SELECIONAR NÉ IDIOTA");
        } else {
            String codAnimalString = String.valueOf(tblAdocao.getValueAt(tblAdocao.getSelectedRow(), 0));
            Integer codAnimal = Integer.valueOf(codAnimalString);

            JFrame telaAnterior = (JFrame) SwingUtilities.getWindowAncestor(this);
            CadastroAdocao telaCadastroAdocao = new CadastroAdocao();
            telaCadastroAdocao.setLocationRelativeTo(telaAnterior);
            telaCadastroAdocao.setVisible(true);
        }
    }//GEN-LAST:event_btnEditaActionPerformed

    private void btnDeletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletaActionPerformed

//        if (tblAdocao.getSelectedRow() == -1) {
//            JOptionPane.showMessageDialog(this, "SÓ ESQUECEU DE SELECIONAR NÉ IDIOTA");
//        } else {
//            String codAnimalString = String.valueOf(tblAdocao.getValueAt(tblAdocao.getSelectedRow(), 0));
//            Integer codAnimal = Integer.valueOf(codAnimalString);
//
//            int confirmacao = JOptionPane.showConfirmDialog(this, "TEM CERTEZA QUE DESEJA DELETAR?");
//
//            if (confirmacao == 0) {
//                boolean deuCerto = controlaAdocao.deletar(codAnimal);
//                if (deuCerto) {
//                    JOptionPane.showMessageDialog(this, "DELETADO COM SUCESSO");
//                    montaTabela();
//                } else {
//                    JOptionPane.showMessageDialog(this, "FALHA AO DELETAR, TENTE NOVAMENTE");
//                    montaTabela();
//                }
//
//            }
//
//        }
    }//GEN-LAST:event_btnDeletaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualiza;
    private javax.swing.JButton btnCadastra;
    private javax.swing.JButton btnDeleta;
    private javax.swing.JButton btnEdita;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAdocao;
    // End of variables declaration//GEN-END:variables
}
