/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import controladores.ControlaAnimal;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.AbstractTableModel;
import modelos.Animal;

/**
 *
 * @author leonardo.bourscheid
 */
public class TelaListagemAnimal extends javax.swing.JInternalFrame {

    ControlaAnimal controlaAnimal = new ControlaAnimal();

    /**
     * Creates new form TelaListagemAnimal
     */
    public TelaListagemAnimal() {
        initComponents();
        montaTabela();
    }

    protected final void montaTabela() {
        ArrayList<Animal> animais = controlaAnimal.recuperarTudo();
        if (animais == null) {
            JOptionPane.showMessageDialog(this, "Erro, nÃ£o foi possivel recuperar");
        } else {
            tblAnimal.setModel(new AbstractTableModel() {
                @Override
                public String getColumnName(int column) {
                    switch (column) {
                        case 0:
                            return "CODIGO";
                        case 1:
                            return "TIPO";
                        case 2:
                            return "RAÇA";
                        case 3:
                            return "DATA ENCONTRO";
                        case 4:
                            return "LOCAL ENCONTRO";
                        case 5:
                            return "SEXO";
                        case 6:
                            return "COR";
                        case 7:
                            return "NOME";
                        default:
                            return "";
                    }
                }

                @Override
                public int getColumnCount() {
                    return 8;
                }

                @Override
                public int getRowCount() {
                    return animais.size();
                }

                @Override
                public Object getValueAt(int rowIndex, int columnIndex) {
                    Animal animal = animais.get(rowIndex);
                    if (animais != null) {
                        switch (columnIndex) {
                            case 0:
                                return animal.getCodAnimal();
                            case 1:
                                return animal.getTipo();
                            case 2:
                                return animal.getRaca();
                            case 3:
                                return animal.getDataEncontro();
                            case 4:
                                return animal.getLocalDeEncontro();
                            case 5:
                                return animal.getSexo();
                            case 6:
                                return animal.getCor();
                            case 7:
                                return animal.getNome();
                        }

                    }

                    return "n/d";
                }
            });

            tblAnimal.getColumnModel().getColumn(0).setMinWidth(80);
            tblAnimal.getColumnModel().getColumn(1).setMinWidth(80);
            tblAnimal.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblAnimal.getColumnModel().getColumn(0).setMaxWidth(20);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnimal = new javax.swing.JTable();
        btnCadastra = new javax.swing.JButton();
        btnAtualiza = new javax.swing.JButton();
        btnEdita = new javax.swing.JButton();
        btnDeleta = new javax.swing.JButton();

        setClosable(true);

        tblAnimal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAnimal);

        btnCadastra.setText("CADASTRA");
        btnCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastraActionPerformed(evt);
            }
        });

        btnAtualiza.setText("ATUALIZA");
        btnAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizaActionPerformed(evt);
            }
        });

        btnEdita.setText("EDITA");
        btnEdita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditaActionPerformed(evt);
            }
        });

        btnDeleta.setText("DELETA");
        btnDeleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtualiza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleta)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastra)
                    .addComponent(btnAtualiza)
                    .addComponent(btnEdita)
                    .addComponent(btnDeleta))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastraActionPerformed
        JFrame telaAnterior = (JFrame) SwingUtilities.getWindowAncestor(this);
        CadastroAnimal telaCadastroAnimal = new CadastroAnimal(telaAnterior, true, controlaAnimal, this);
        telaCadastroAnimal.setLocationRelativeTo(telaAnterior);
        telaCadastroAnimal.setVisible(true);
    }//GEN-LAST:event_btnCadastraActionPerformed

    private void btnAtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizaActionPerformed
        montaTabela();
    }//GEN-LAST:event_btnAtualizaActionPerformed

    private void btnDeletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletaActionPerformed

        String codAnimalString = String.valueOf(tblAnimal.getValueAt(tblAnimal.getSelectedRow(), 0));
        Integer codAnimal = Integer.valueOf(codAnimalString);

        int confirmacao = JOptionPane.showConfirmDialog(this, "TEM CERTEZA QUE DESEJA DELETAR?");

        if (confirmacao == 0) {
            boolean deuCerto = controlaAnimal.deletar(codAnimal);
            if (deuCerto) {
                JOptionPane.showMessageDialog(this, "DELETADO COM SUCESSO");
                montaTabela();
            } else {
                JOptionPane.showMessageDialog(this, "FALHA AO DELETAR, TENTE NOVAMENTE");
                montaTabela();
            }

        }


    }//GEN-LAST:event_btnDeletaActionPerformed

    private void btnEditaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditaActionPerformed

        String codAnimalString = String.valueOf(tblAnimal.getValueAt(tblAnimal.getSelectedRow(), 0));
        Integer codAnimal = Integer.valueOf(codAnimalString);

        JFrame telaAnterior = (JFrame) SwingUtilities.getWindowAncestor(this);
        CadastroAnimal telaCadastroAnimal = new CadastroAnimal(telaAnterior, true, controlaAnimal, this, codAnimal);
        telaCadastroAnimal.setLocationRelativeTo(telaAnterior);
        telaCadastroAnimal.setVisible(true);

    }//GEN-LAST:event_btnEditaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualiza;
    private javax.swing.JButton btnCadastra;
    private javax.swing.JButton btnDeleta;
    private javax.swing.JButton btnEdita;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAnimal;
    // End of variables declaration//GEN-END:variables
}
