/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import controladores.ControlaPessoa;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import modelos.Pessoa;

/**
 *
 * @author leonardo.bourscheid
 */
public class TelaListagemPessoa extends javax.swing.JInternalFrame {

    ControlaPessoa controlaPessoa = new ControlaPessoa();

    /**
     * Creates new form TelaListagemPessoa
     */
    public TelaListagemPessoa() {
        initComponents();
        montaTabela();
    }

    protected final void montaTabela() {
        ArrayList<Pessoa> pessoas = controlaPessoa.recuperarTudo();
        if (pessoas == null) {
            JOptionPane.showMessageDialog(this, "Erro, não foi possivel recuperar");
        } else {
            tblPessoa.setModel(new AbstractTableModel() {
                @Override
                public String getColumnName(int column) {
                    switch (column) {
                        case 0:
                            return "CÓDIGO";
                        case 1:
                            return "NOME";
                        case 2:
                            return "CPF";
                        case 3:
                            return "ENDEREÇO";
                        case 4:
                            return "NASCIMENTO";
                        default:
                            return "";
                    }
                }

                @Override
                public int getColumnCount() {
                    return 5;
                }

                @Override
                public int getRowCount() {
                    return pessoas.size();
                }

                @Override
                public Object getValueAt(int rowIndex, int columnIndex) {
                    Pessoa pessoa = pessoas.get(rowIndex);

                    if (pessoa != null) {
                        switch (columnIndex) {
                            case 0:
                                return pessoa.getCodPessoa();
                            case 1:
                                return pessoa.getNomePessoa();
                            case 2:
                                return pessoa.getCpf();
                            case 3:
                                return pessoa.getEndereco();
                            case 4:
                                return pessoa.getDataNascimento();
                        }

                    }

                    return "n/d";
                }
            });

            tblPessoa.getColumnModel().getColumn(0).setMinWidth(80);
            tblPessoa.getColumnModel().getColumn(1).setMinWidth(180);
            tblPessoa.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblPessoa.getColumnModel().getColumn(0).setMaxWidth(20);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPessoa = new javax.swing.JTable();
        btnCadastra = new javax.swing.JButton();
        btnAtualiza = new javax.swing.JButton();
        btnDeleta = new javax.swing.JButton();
        btnEdita = new javax.swing.JButton();

        setClosable(true);

        tblPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPessoa);

        btnCadastra.setText("CADASTRA");
        btnCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastraActionPerformed(evt);
            }
        });

        btnAtualiza.setText("ATUALIZA");
        btnAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizaActionPerformed(evt);
            }
        });

        btnDeleta.setText("DELETA");

        btnEdita.setText("EDITA");
        btnEdita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtualiza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleta)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastra)
                    .addComponent(btnAtualiza)
                    .addComponent(btnDeleta)
                    .addComponent(btnEdita))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastraActionPerformed

        CadastroPessoa telaCadastroPessoa = new CadastroPessoa(null, true, controlaPessoa);
        telaCadastroPessoa.setVisible(true);

    }//GEN-LAST:event_btnCadastraActionPerformed

    private void btnAtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizaActionPerformed
        montaTabela();
    }//GEN-LAST:event_btnAtualizaActionPerformed

    private void btnEditaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualiza;
    private javax.swing.JButton btnCadastra;
    private javax.swing.JButton btnDeleta;
    private javax.swing.JButton btnEdita;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPessoa;
    // End of variables declaration//GEN-END:variables
}
