/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import apoio.Formatacao;
import controladores.ControlaAdocao;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.AbstractTableModel;
import modelos.Adocao;
import static modelos.Adocao.Status.CONFIRMADO;
import static modelos.Adocao.Status.DEVOLVIDO;

import modelos.Pessoa;

/**
 *
 * @author leonardo.bourscheid
 */
public class TelaListagemAdocao extends javax.swing.JInternalFrame {
    
    ControlaAdocao controlaAdocao = ControlaAdocao.getInstance();
    
    private static TelaListagemAdocao instance = null;
    
    /**
     * Creates new form TelaListagemAdocao
     */
    public TelaListagemAdocao() {
        initComponents();
        montaTabela();
    }
    
    public static TelaListagemAdocao getInstance() {
        if (instance == null) {
            instance = new TelaListagemAdocao();
        }
        return instance;
    }

    public final void montaTabela() {
        ArrayList<Adocao> adocoes = controlaAdocao.recuperarTodos();
        if (adocoes == null) {
            JOptionPane.showMessageDialog(this, "Erro, não foi possivel recuperar");
        } else {
            tblAdocao.setModel(new AbstractTableModel() {
                @Override
                public String getColumnName(int column) {
                    switch (column) {
                        case 0:
                            return "ID";
                        case 1:
                            return "PESSOA";
                        case 2:
                            return "ANIMAL";
                        case 3:
                            return "STATUS";
                        case 4:
                            return "DATA ADOCAO";
                        default:
                            return "";
                    }
                }

                @Override
                public int getColumnCount() {
                    return 5;
                }

                @Override
                public int getRowCount() {
                    return adocoes.size();
                }

                @Override
                public Object getValueAt(int rowIndex, int columnIndex) {
                    Adocao adocao = adocoes.get(rowIndex);

                    boolean validaData = !(adocao.getDataAdocao() == null);
                    
                    if (adocao != null) {
                        switch (columnIndex) {
                            case 0:
                                return adocao.getCodAdocao();
                            case 1:
                                return adocao.getPessoa().getNomePessoa();
                            case 2:
                                return adocao.getAnimal().getResumoPet();
                            case 3:
                                return adocao.getStatus().getNome();
                            case 4:
                                return validaData ? adocao.getDataAdocao() : "";
                        }

                    }

                    return "n/d";
                }
            });

            tblAdocao.getColumnModel().getColumn(0).setMinWidth(35);
            tblAdocao.getColumnModel().getColumn(1).setMinWidth(180);
            tblAdocao.getColumnModel().getColumn(2).setMinWidth(180);
            tblAdocao.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblAdocao.getColumnModel().getColumn(0).setMaxWidth(40);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastra = new javax.swing.JButton();
        btnConfirma = new javax.swing.JButton();
        btnEdita = new javax.swing.JButton();
        btnDeleta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdocao = new javax.swing.JTable();
        btnDevolve = new javax.swing.JButton();

        setClosable(true);
        setMinimumSize(new java.awt.Dimension(655, 507));
        setPreferredSize(new java.awt.Dimension(655, 507));

        btnCadastra.setText("CADASTRA");
        btnCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastraActionPerformed(evt);
            }
        });

        btnConfirma.setText("CONFIRMA");
        btnConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmaActionPerformed(evt);
            }
        });

        btnEdita.setText("EDITA");
        btnEdita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditaActionPerformed(evt);
            }
        });

        btnDeleta.setText("DELETA");
        btnDeleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletaActionPerformed(evt);
            }
        });

        tblAdocao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAdocao);

        btnDevolve.setText("DEVOLVE");
        btnDevolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDevolve)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleta)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastra)
                    .addComponent(btnConfirma)
                    .addComponent(btnEdita)
                    .addComponent(btnDeleta)
                    .addComponent(btnDevolve))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastraActionPerformed
        JFrame telaAnterior = (JFrame) SwingUtilities.getWindowAncestor(this);
        CadastroAdocao telaCadastroAdocao = new CadastroAdocao(telaAnterior, true);
        telaCadastroAdocao.setLocationRelativeTo(telaAnterior);
        telaCadastroAdocao.setVisible(true);
    }//GEN-LAST:event_btnCadastraActionPerformed

    private void btnConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmaActionPerformed
        Adocao adocao = recuperaAdocaoTabela(recuperaIdTabela());
        
        if (adocao != null && adocao.getStatus().equals(Adocao.Status.PENDENTE)) {
            int confirmacao = JOptionPane.showConfirmDialog(this, "DESEJA MESMO CONFIRMAR ESSA ADOCAO?");
            
            if (confirmacao == 0) {
                adocao.setStatus(Adocao.Status.CONFIRMADO);
                adocao.setDataAdocao(LocalDate.now());

                boolean deuCerto = controlaAdocao.editar(adocao);

                if (deuCerto) {
                    JOptionPane.showMessageDialog(this, "ADOCAO CONFIRMADA COM SUCESSO!");
                } else {
                    JOptionPane.showMessageDialog(this, "ERRO AO CONFIRMAR ADOCAO, TENTE NOVAMENTE!");
                }

                montaTabela();
            }
            
        } else if (adocao != null) {
            switch (adocao.getStatus()) {
                case CONFIRMADO -> {
                    JOptionPane.showMessageDialog(this, "ESTA ADOCAO JA FOI CONFIRMADA!");
                }
                
                case DEVOLVIDO -> {
                    JOptionPane.showMessageDialog(this, "NAO E POSSIVEL CONFIRMAR UMA ADOCAO DEVOLVIDA!");
                }
            }
        }
    }//GEN-LAST:event_btnConfirmaActionPerformed

    private void btnEditaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditaActionPerformed
        Adocao adocao = recuperaAdocaoTabela(recuperaIdTabela());
        
        if (adocao != null && adocao.getStatus().equals(Adocao.Status.PENDENTE)) {
            JFrame telaAnterior = (JFrame) SwingUtilities.getWindowAncestor(this);
            CadastroAdocao telaCadastroAdocao = new CadastroAdocao(telaAnterior, true, adocao);
            telaCadastroAdocao.setLocationRelativeTo(telaAnterior);
            telaCadastroAdocao.setVisible(true);
        } else if (adocao != null) {
            switch (adocao.getStatus()) {
                case CONFIRMADO -> {
                    JOptionPane.showMessageDialog(this, "NAO E POSSIVEL EDITAR UMA ADOCAO CONFIRMADA!");
                }
                
                case DEVOLVIDO -> {
                    JOptionPane.showMessageDialog(this, "NAO E POSSIVEL EDITAR UMA ADOCAO DEVOLVIDA!");
                }
            }
        }
    }//GEN-LAST:event_btnEditaActionPerformed

    private void btnDeletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletaActionPerformed
        Adocao adocao = recuperaAdocaoTabela(recuperaIdTabela());
        
        if (adocao != null && adocao.getStatus().equals(Adocao.Status.PENDENTE)) {
            int confirmacao = JOptionPane.showConfirmDialog(this, "TEM CERTEZA QUE DESEJA DELETAR?");

            if (confirmacao == 0) {
                boolean deuCerto = controlaAdocao.deletar(adocao.getCodAdocao());
                if (deuCerto) {
                    JOptionPane.showMessageDialog(this, "DELETADO COM SUCESSO");
                    montaTabela();
                } else {
                    JOptionPane.showMessageDialog(this, "FALHA AO DELETAR, TENTE NOVAMENTE");
                    montaTabela();
                }

            }

        } else if (adocao != null) {
            switch (adocao.getStatus()) {
                case CONFIRMADO -> {
                    JOptionPane.showMessageDialog(this, "NAO E POSSIVEL DELETAR UMA ADOCAO CONFIRMADA!");
                }
                
                case DEVOLVIDO -> {
                    JOptionPane.showMessageDialog(this, "NAO E POSSIVEL DELETAR UMA ADOCAO DEVOLVIDA!");
                }
            }
        }
    }//GEN-LAST:event_btnDeletaActionPerformed

    private void btnDevolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolveActionPerformed
        Adocao adocao = recuperaAdocaoTabela(recuperaIdTabela());
        
        if (adocao != null && adocao.getStatus().equals(Adocao.Status.CONFIRMADO)) {
            JFrame telaAnterior = (JFrame) SwingUtilities.getWindowAncestor(this);
            CadastroAdocao telaCadastroAdocao = new CadastroAdocao(telaAnterior, true, adocao);
            telaCadastroAdocao.setLocationRelativeTo(telaAnterior);
            telaCadastroAdocao.setVisible(true);
        } else if (adocao != null) {
            switch (adocao.getStatus()) {
                case PENDENTE -> {
                    JOptionPane.showMessageDialog(this, "ESSA ADOCAO AINDA NAO FOI CONFIRMADA!");
                }
                
                case DEVOLVIDO -> {
                    JOptionPane.showMessageDialog(this, "ESSA ADOCAO JA FOI DEVOLVIDA!");
                }
            }
        }
        
    }//GEN-LAST:event_btnDevolveActionPerformed

    private int recuperaIdTabela() {
        String idString = String.valueOf(tblAdocao.getValueAt(tblAdocao.getSelectedRow(), 0));
        int id = Integer.parseInt(idString);
        
        return id;
    }
    
    private Adocao recuperaAdocaoTabela(int codAdocao) {
        Adocao adocao = null;
        
        if (codAdocao == -1) {
            JOptionPane.showMessageDialog(this, "SÓ ESQUECEU DE SELECIONAR NÉ IDIOTA");
        } else {
            adocao = controlaAdocao.recuperarPorId(codAdocao);
        }
        
        return adocao;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastra;
    private javax.swing.JButton btnConfirma;
    private javax.swing.JButton btnDeleta;
    private javax.swing.JButton btnDevolve;
    private javax.swing.JButton btnEdita;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAdocao;
    // End of variables declaration//GEN-END:variables
}
