/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import apoio.PDFManager;
import controladores.ControlaAnimal;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import modelos.Animal;

/**
 *
 * @author leonardobourscheid
 */
public class TelaPDFAnimal extends javax.swing.JInternalFrame {

    ControlaAnimal controlaAnimal = ControlaAnimal.getInstance();
    
    /**
     * Creates new form TelaPDFAnimal
     */
    public TelaPDFAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCaminho = new javax.swing.JTextField();
        btnGerarPDF = new javax.swing.JButton();
        btnSelecionarCaminho = new javax.swing.JButton();

        setClosable(true);

        btnGerarPDF.setText("Gerar PDF");
        btnGerarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarPDFActionPerformed(evt);
            }
        });

        btnSelecionarCaminho.setText("Selecionar caminho");
        btnSelecionarCaminho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarCaminhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCaminho)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSelecionarCaminho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(btnGerarPDF)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelecionarCaminho)
                    .addComponent(btnGerarPDF))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarPDFActionPerformed

        String caminho = txtCaminho.getText();
        ArrayList<Animal> animais = controlaAnimal.recuperarTudo();

        if (!animais.isEmpty()) {
            if (caminho.isBlank()) {
                JOptionPane.showMessageDialog(this, "VOCÊ PRECISA SELECIONAR UM CAMINHO PARA GERAR O PDF!");
            } else {
                try {
                    String[] ordem = {
                        "codAnimal",
                        "tipo",
                        "raca",
                        "cor",
                        "sexo",
                        "localDeEncontro",
                        "dataEncontro"
                    };

                    String[] rotulos = {
                        "Código",
                        "Tipo",
                        "Raça",
                        "Cor",
                        "Sexo",
                        "Local de Encontro",
                        "Data de Encontro"
                    };

                    int[] larguras = {6, 8, 8, 8, 5, 17, 16};

                    PDFManager.gerar(animais, caminho, ordem, larguras, rotulos);
                    JOptionPane.showMessageDialog(this, "PDF GERADO COM SUCESSO, NO CAMINHO: " + caminho);
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, "OCORREU UM ERRO AO GERAR O PDF, TENTE NOVAMENTE MAIS TARDE");
                    System.err.println("Erro ao salvar PDF: " + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "NÃO HÁ ANIMAIS CADASTRADOS");
        }

    }//GEN-LAST:event_btnGerarPDFActionPerformed

    private void btnSelecionarCaminhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarCaminhoActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Escolha um caminho para salvar o arquivo");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        int resultado = chooser.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File dir = chooser.getSelectedFile();
            txtCaminho.setText(dir.getAbsolutePath() + "/animais.pdf");
        }
    }//GEN-LAST:event_btnSelecionarCaminhoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarPDF;
    private javax.swing.JButton btnSelecionarCaminho;
    private javax.swing.JTextField txtCaminho;
    // End of variables declaration//GEN-END:variables
}
